#include "cpp_generator.h"
#include <sstream>
#include <vector>
#include <algorithm>
#include <chrono>
#include <set>
#include <fmt/format.h>

using namespace enumbra;
using namespace enumbra::cpp;

std::string to_upper(const std::string& str)
{
	std::string strcopy = str;
	std::transform(strcopy.begin(), strcopy.end(), strcopy.begin(), ::toupper);
	return strcopy;
}

const enum_entry& get_enum_entry_value(const ValueEnumDefaultValueStyle& style, const enum_definition& definition)
{
	switch (style)
	{
	case ValueEnumDefaultValueStyle::Min:
	{
		auto& m = std::min_element(definition.values.begin(), definition.values.end(),
			[](const enum_entry& lhs, const enum_entry& rhs) { return lhs.value < rhs.value; });
		if (m != definition.values.end())
		{
			return *m;
		}
		else
		{
			throw std::runtime_error("get_value_enum_default_value_style_string: ValueEnumDefaultValueStyle::Min failed somehow.");
		}
		break;
	}
	case ValueEnumDefaultValueStyle::Max:
	{
		auto& m = std::max_element(definition.values.begin(), definition.values.end(),
			[](const enum_entry& lhs, const enum_entry& rhs) { return lhs.value < rhs.value; });
		if (m != definition.values.end())
		{
			return *m;
		}
		else
		{
			throw std::runtime_error("get_value_enum_default_value_style_string: ValueEnumDefaultValueStyle::Max failed somehow.");
		}
		break;
	}
	case ValueEnumDefaultValueStyle::First:
	{
		return definition.values.front();
	}
	case ValueEnumDefaultValueStyle::Last:
	{
		return definition.values.back();
	}
	default:
		throw std::runtime_error("value_enum_default_value_style: Invalid ValueEnumDefaultValueStyle");
	}
}

// Log2 of unsigned int
constexpr uint64_t Log2Unsigned(uint64_t x)
{
	if (x == 0)
	{
		return 0;
	}

	int targetlevel = 0;
	while (x >>= 1)
		++targetlevel;
	return targetlevel;
}

const std::string& cpp_generator::generate_cpp_output(const enumbra_config& cfg, const enumbra::enum_meta_config& enum_meta)
{
	auto& cpp = cfg.cpp_config;
	Output.clear();

	// Setting up re-usable tokens
	LF = (cpp.line_ending_style == cpp::LineEndingStyle::LF) ? "\n" : "\r\n";
	TAB = cpp.output_tab_characters;
	const std::string def_macro = fmt::format("ENUMBRA_{}_H", to_upper(enum_meta.block_name));
	
	// Enumbra pre-preamble
	std::time_t time_point = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
	char time_buf[255];
	ctime_s(time_buf, 255, &time_point);
	write_line("// This file was generated by enumbra version {} on: {}", kEnumbraVersion, time_buf);
	write_line("// The enumbra project is hosted at: https://github.com/Scaless/enumbra");
	write_linefeed();

	// Custom preamble
	for (const auto& line : cpp.preamble_text) {
		write_line(line);
	}

	// INCLUDE GUARD
	switch (cpp.include_guard_style)
	{
	case enumbra::cpp::IncludeGuardStyle::None:
	{
		break;
	}
	case enumbra::cpp::IncludeGuardStyle::PragmaOnce:
	{
		write("#pragma once");
		write_linefeed(2);
		break;
	}
	case enumbra::cpp::IncludeGuardStyle::CStyle:
	{
		write("#ifndef {0}{1}#define {0}{1}{1}", def_macro, LF);
		break;
	}
	default:
		throw std::runtime_error("include_guard_wrap: Invalid IncludeGuardStyle");
	}

	// INCLUDES
	for (const auto& inc : cpp.additional_includes) {
		write_line("#include {}", inc);
	}
	if (cpp.string_table_layout != StringTableLayout::None) {
		if (cpp.string_table_type == StringTableType::ConstexprStringView || cpp.string_table_type == StringTableType::ConstexprWStringView)
		{
			write_line("#include <string_view>");
		}
	}
	write_linefeed();

	// MACRO DEFINITIONS
	if (cfg.cpp_config.packed_declaration_macros)
	{
		write("#define ENUMBRA_PACK(Enum, Name) Enum##::Value Name : Enum##::bits_required_storage();");
		write_linefeed(2);
	}

	// START CONFIG NAMESPACE
	for (const auto& ns : cpp.output_namespace) {
		write_line("namespace {} {{", ns);
	}
	write_linefeed();

	// VALUE ENUM DEFINITIONS
	for (auto& e : enum_meta.value_enum_definitions) {

		// Precondition checks
		// 1. Enum value names must be unique
		std::set<std::string> seen_names;
		for (auto& v : e.values)
		{
			auto& seen = seen_names.find(v.name);
			if (seen != seen_names.end())
			{
				throw std::runtime_error("ENUM DEFINITIONS Precondition Check 1: Enum Value Name is not unique (name = " + *seen + ")");
			}
			seen_names.insert(v.name);
		}
		seen_names.clear();
		// 2. Enum must have at least 1 value
		if (e.values.size() == 0)
		{
			throw std::runtime_error("ENUM DEFINITIONS Precondition Check 2: Enum does not contain any values (name = " + e.name + ")");
		}

		// Get references and metadata for relevant enum values that we will need
		const enum_entry& default_entry = get_enum_entry_value(enum_meta.value_enum_default_value_style, e);
		const enum_entry& min_entry = get_enum_entry_value(ValueEnumDefaultValueStyle::Min, e);
		const enum_entry& max_entry = get_enum_entry_value(ValueEnumDefaultValueStyle::Max, e);
		const size_t entry_count = e.values.size();
		const size_t bits_required_storage = Log2Unsigned(max_entry.value) + 1;

		// Determine if all values are unique, or if some enum value names overlap.
		// TODO: Enforce if flag is set
		std::set<int64_t> unique_values;
		for (auto& v : e.values) { unique_values.insert(v.value); }
		const size_t unique_entry_count = unique_values.size();

		// Determine if range is contiguous
		// Enables some minor optimizations for range-checking values if true
		// TODO: Enforce if flag is set
		bool is_contiguous = true;
		int64_t value = *unique_values.begin();
		bool skip_first = true;
		for (auto& u : unique_values)
		{
			if (skip_first) {
				skip_first = false;
				continue;
			}
			if (u != (value + 1))
			{
				is_contiguous = false;
				break;
			}
			value++;
		}

		// BEGIN CLASS GENERATION
		write_line("class {} {{", e.name);
		write_line("public:");
		write_line_tabbed(1, "using value_type = {};", cpp.get_size_type_from_index(e.size_type_index).generated_name);

		// Internal enum class
		write_line_tabbed(1, "enum class Value : value_type {{");
		for (const auto& v : e.values) {
			write_line_tabbed(2, "{} = {},", v.name, v.value);
		}
		write_line_tabbed(1, "}};");
		write_linefeed();

		// Static values
		for (const auto& v : e.values) {
			write_line_tabbed(1, "constexpr static Value {0} = Value::{0};", v.name);
		}
		write_linefeed();

		// Default Constructor
		write_line_tabbed(1, "constexpr {}() : value(Value::{}) {{ }}", e.name, default_entry.name);

		// Value Constructor
		write_line_tabbed(1, "constexpr {}(Value v) : value(v) {{ }}", e.name);

		// Operators
		write_line_tabbed(1, "constexpr operator Value() const {{ return value; }}");
		write_line_tabbed(1, "constexpr bool operator==({} other) const {{ return value == other.value; }}", e.name);
		write_line_tabbed(1, "constexpr bool operator!=({} other) const {{ return value != other.value; }}", e.name);
		write_line_tabbed(1, "constexpr explicit operator bool() = delete;");

		write_linefeed();

		// Introspection functions
		write_line_tabbed(1, "constexpr static value_type min() {{ return {}; }}", min_entry.value);
		write_line_tabbed(1, "constexpr static value_type max() {{ return {}; }}", max_entry.value);
		write_line_tabbed(1, "constexpr static size_t count() {{ return {}; }}", unique_entry_count);
		write_line_tabbed(1, "constexpr static size_t nonunique_count() {{ return {}; }}", entry_count);
		write_line_tabbed(1, "constexpr static bool is_contiguous() {{ return {}; }}", (is_contiguous ? "true" : "false"));
		write_line_tabbed(1, "constexpr value_type to_underlying() {{ return static_cast<value_type>(value); }}");
		write_line_tabbed(1, "constexpr static value_type to_underlying(Value v) {{ return static_cast<value_type>(v); }}");
		write_line_tabbed(1, "constexpr static Value from_underlying_unsafe(value_type v) {{ return static_cast<Value>(v); }}");
		write_line_tabbed(1, "constexpr static value_type bits_required_storage() {{ return {}; }}", bits_required_storage);

		write_linefeed();

		// Value functions
		write_line_tabbed(1, "constexpr auto begin() noexcept {{ return Values.begin(); }}");
		write_line_tabbed(1, "constexpr auto end() noexcept {{ return Values.end(); }}");

		// If values in the enum are fully contiguous, we can check validity with a simple bounds check. Otherwise we need to scan the values table.
		if (is_contiguous) {
			write_line_tabbed(1, "constexpr static bool contains(Value v) {{ return ({} <= to_underlying(v)) && (to_underlying(v) <= {}); }}", min_entry.value, max_entry.value);
			write_line_tabbed(1, "constexpr static bool contains(value_type v) {{ return ({} <= v) && (v <= {}); }}", min_entry.value, max_entry.value);
		}
		else
		{
			write_line_tabbed(1, "constexpr static bool contains(Value v) {{ return std::find(Values.begin(), Values.end(), v) != Values.end(); }}");
			write_line_tabbed(1, "constexpr static bool contains(value_type v) {{ return std::find(Values.begin(), Values.end(), static_cast<Value>(v)) != Values.end(); }}");
		}

		// Array of values
		write_line_tabbed(1, "constexpr static std::array<Value, {}> Values = {{", unique_entry_count);
		for (const auto& v : e.values) {
			write_line_tabbed(2, "Value::{},", v.name);
		}
		write_line_tabbed(1, "}};");

		// Private storage
		write_line("private:");
		write_line_tabbed(1, "Value value;");

		// END CLASS
		write_line("}};");
		write_linefeed();

		// Extra functions?

	}

	// END CONFIG NAMESPACE
	write_linefeed();
	for (auto& ns = cpp.output_namespace.rbegin(); ns != cpp.output_namespace.rend(); ++ns) {
		write_line("}} // namespace ", *ns);
	}

	// END INCLUDE GUARD
	if (cpp.include_guard_style == IncludeGuardStyle::CStyle) {
		write_line("#endif // {}", def_macro);
	}

	return Output;
}

std::vector<cpp_enum_generated> cpp_generator::generate_enums(const cpp_enum_config_final& cfg)
{
	throw std::logic_error("Unimplemented");
}
